CC := g++-5
WARNING_FLAGS := -Wall
# WARNING_FLAGS := -pedantic -Wall -Wextra -Wcast-align -Wcast-qual -Wctor-dtor-privacy -Wdisabled-optimization -Wformat=2 -Winit-self -Wlogical-op -Wmissing-declarations -Wmissing-include-dirs -Wnoexcept -Wold-style-cast -Woverloaded-virtual -Wredundant-decls -Wshadow -Wsign-conversion -Wsign-promo -Wstrict-null-sentinel -Wswitch-default -Wundef -Werror -Wno-unused -Wstrict-overflow=5
# WARNING_FLAGS := -pedantic -Wall -Wextra -Wcast-align -Wcast-qual -Wctor-dtor-privacy -Wdisabled-optimization -Wformat=2 -Winit-self -Wlogical-op -Wmissing-declarations -Wmissing-include-dirs -Wnoexcept -Wold-style-cast -Woverloaded-virtual -Wredundant-decls -Wshadow -Wsign-conversion -Wsign-promo -Wstrict-null-sentinel -Wswitch-default -Wundef -Werror -Wno-unused -Wstrict-overflow=2
CFLAGS := -lgtest -lgtest_main -pthread -std=c++17 -O3 $(WARNING_FLAGS)

all: test

test: test.o
	$(CC) -o test test.o $(CFLAGS)

test.o: ../sorting/bogosort.hpp ../sorting/bubbleSort.hpp ../sorting/heapsort.hpp ../sorting/insertionSort.hpp ../sorting/introsort.hpp ../sorting/mergeSort.hpp ../sorting/quicksort.hpp test.cpp
	$(CC) -c test.cpp -I../sorting/ $(CFLAGS)

clean:
	$(RM) *.o
