CC := g++-5
WARNING_FLAGS := -Wall
# WARNING_FLAGS := -pedantic -Wall -Wextra -Wcast-align -Wcast-qual -Wctor-dtor-privacy -Wdisabled-optimization -Wformat=2 -Winit-self -Wlogical-op -Wmissing-declarations -Wmissing-include-dirs -Wnoexcept -Wold-style-cast -Woverloaded-virtual -Wredundant-decls -Wshadow -Wsign-conversion -Wsign-promo -Wstrict-null-sentinel -Wswitch-default -Wundef -Werror -Wno-unused -Wstrict-overflow=5
# WARNING_FLAGS := -pedantic -Wall -Wextra -Wcast-align -Wcast-qual -Wctor-dtor-privacy -Wdisabled-optimization -Wformat=2 -Winit-self -Wlogical-op -Wmissing-declarations -Wmissing-include-dirs -Wnoexcept -Wold-style-cast -Woverloaded-virtual -Wredundant-decls -Wshadow -Wsign-conversion -Wsign-promo -Wstrict-null-sentinel -Wswitch-default -Wundef -Werror -Wno-unused -Wstrict-overflow=2
CFLAGS := -std=c++17 -O3 $(WARNING_FLAGS)

all: sortTesting

sortTesting: sortTesting.o
	$(CC) -o sortTesting sortTesting.o $(CFLAGS)

sortTesting.o: sortTesting.cpp heapsort.hpp insertionSort.hpp introsort.hpp quicksort.hpp timeUtility.hpp
	$(CC) -c sortTesting.cpp $(CFLAGS)

clean:
	$(RM) *.o
